### ISSUE TITLE
Give Gorges more control over tunnels

### ISSUE THREAD

**Issue by keatsandyeats** [Steelcap/NSL-CompMod#10]
In vanilla, when gorges place a third tunnel, their oldest tunnel is destroyed. Gorges cannot choose which tunnel they want their new one to replace. Let's allow Gorges to replace either tunnel without having to manually delete one.

Possible solution from old compmod: Split the tunnel build menu item into Entrance and Exit.
Possible solution from Steel: Holding (or not) a certain key while placing a new tunnel will destroy the most recent tunnel (or oldest).

**Comment by Steelcap** [comment]
Resolved with update
