### ISSUE TITLE
"Evolve last upgrades" is free if you already have upgrades

### ISSUE THREAD

**Issue by keatsandyeats** [Steelcap/NSL-CompMod#5]
If you use "Evolve last upgrades" when you already have an upgrade, you will egg anyway and come out with those upgrades again. Even if you are a higher lifeform, this will not cost you pres. Aliens always come out of an egg with full energy, so this is a quick way to fill your energy for free.

Possible solution: 
Disable "Evolve last upgrades" if you already have an upgrade.

Vanilla is also looking to fix this: https://trello.com/c/cYVB9XN4/452-308-evolve-last-upgrades-gives-you-energy-for-free

**Comment by keatsandyeats** [comment]
possible fix: add a check for upgrades in function `OnCommandEvolveLastUpgrades` in `/ns2/lua/NS2ConsoleCommands_Server.lua` line 1530

**Comment by Steelcap** [comment]
I proposed a vanilla solution as this is an issue not only for the comp community.
